//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyCatalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyCatalogue()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ItemId { get; set; }
        public int SuppliersSupplierId { get; set; }
        public int ProductsProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Suppliers Supplier { get; set; }
        public virtual Products Product { get; set; }
    }
}
